version: '3.8'

services:
  db:
    image: postgres:15-alpine # Versión ligera de Postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: rust_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://admin:supersecretpassword@db:5432/rust_db
      - JWT_SECRET=mi_secreto_super_seguro_12345
    depends_on:
      - db

volumes:
  pgdata: